# This rule is not used by the project image-cache-agent itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to image-cache.scality.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: image-cache-agent
    app.kubernetes.io/managed-by: kustomize
  name: imagecache-viewer-role
rules:
- apiGroups:
  - image-cache.scality.com
  resources:
  - imagecaches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image-cache.scality.com
  resources:
  - imagecaches/status
  verbs:
  - get
