---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - image-cache.scality.com
  resources:
  - imagecaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image-cache.scality.com
  resources:
  - imagecaches/finalizers
  verbs:
  - update
- apiGroups:
  - image-cache.scality.com
  resources:
  - imagecaches/status
  verbs:
  - get
  - patch
  - update
