---
name: Post Merge

on:
  push:
    branches: [main]
    paths:
      - 'agent/**'
      - '.github/workflows/agent-image.yaml'
      - '.github/workflows/post-merge.yaml'

jobs:
  agent-image:
    uses: ./.github/workflows/agent-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      is-latest: true
      is-stable: false
